import type * as schema from '@/db/schema';

export const SpanishUnits: (typeof schema.unit.$inferInsert)[] = [
  {
    id: 1,
    courseId: 1,
    title: 'Unit 1',
    description: 'Learn the basics of the Spanish',
    order: 1,
  },
];

export const SpanishLessons: (typeof schema.lesson.$inferInsert)[] = [
  { id: 1, unitId: 1, order: 1, title: 'Nouns' },
  { id: 2, unitId: 1, order: 2, title: 'Numbers' },
  { id: 3, unitId: 1, order: 3, title: 'Colors' },
  { id: 4, unitId: 1, order: 4, title: 'Family' },
  { id: 5, unitId: 1, order: 5, title: 'Greetings' },
];

export const SpanishChallenges: (typeof schema.challenge.$inferInsert)[] = [
  {
    id: 1,
    lessonId: 1,
    order: 1,
    type: 'SELECT',
    question: 'Which one of these is "the man"?',
  },
  {
    id: 2,
    lessonId: 1,
    order: 2,
    type: 'ASSIST',
    question: '"the man"',
  },
  {
    id: 3,
    lessonId: 1,
    order: 3,
    type: 'SELECT',
    question: 'Which one of these is "the robot"?',
  },
  {
    id: 4,
    lessonId: 2,
    order: 1,
    type: 'SELECT',
    question: 'Which one means "three"?',
  },
  {
    id: 5,
    lessonId: 2,
    order: 2,
    type: 'ASSIST',
    question: '"seven"',
  },
  {
    id: 6,
    lessonId: 3,
    order: 1,
    type: 'SELECT',
    question: 'Which one means "red"?',
  },
  {
    id: 7,
    lessonId: 3,
    order: 2,
    type: 'ASSIST',
    question: '"blue"',
  },
  {
    id: 8,
    lessonId: 4,
    order: 1,
    type: 'SELECT',
    question: 'Which means "mother"?',
  },
  {
    id: 9,
    lessonId: 4,
    order: 2,
    type: 'ASSIST',
    question: '"brother"',
  },
  {
    id: 10,
    lessonId: 5,
    order: 1,
    type: 'SELECT',
    question: 'Which means "hello"?',
  },
  {
    id: 11,
    lessonId: 5,
    order: 2,
    type: 'ASSIST',
    question: '"goodbye"',
  },
];

export const SpanishChallengeOptions: (typeof schema.challengeOption.$inferInsert)[] =
  [
    {
      challengeId: 1,
      text: 'el hombre',
      imageSrc: '/man.svg',
      audioSrc: '/es/es_man.mp3',
      isCorrect: true,
    },
    {
      challengeId: 1,
      text: 'la mujer',
      imageSrc: '/woman.svg',
      audioSrc: '/es/es_woman.mp3',
      isCorrect: false,
    },
    {
      challengeId: 1,
      text: 'el robot',
      imageSrc: '/robot.svg',
      audioSrc: '/es/es_robot.mp3',
      isCorrect: false,
    },
    {
      challengeId: 2,
      text: 'el hombre',
      audioSrc: '/es/es_man.mp3',
      isCorrect: true,
    },
    {
      challengeId: 2,
      text: 'la mujer',
      audioSrc: '/es/es_woman.mp3',
      isCorrect: false,
    },
    {
      challengeId: 2,
      text: 'el robot',
      audioSrc: '/es/es_robot.mp3',
      isCorrect: false,
    },
    {
      challengeId: 3,
      text: 'el hombre',
      imageSrc: '/man.svg',
      audioSrc: '/es/es_man.mp3',
      isCorrect: false,
    },
    {
      challengeId: 3,
      text: 'la mujer',
      imageSrc: '/woman.svg',
      audioSrc: '/es/es_woman.mp3',
      isCorrect: false,
    },
    {
      challengeId: 3,
      text: 'el robot',
      imageSrc: '/robot.svg',
      audioSrc: '/es/es_robot.mp3',
      isCorrect: true,
    },
    {
      challengeId: 4,
      text: 'tres',
      audioSrc: '/es/es_three.mp3',
      isCorrect: true,
    },
    {
      challengeId: 4,
      text: 'dos',
      audioSrc: '/es/es_two.mp3',
      isCorrect: false,
    },
    {
      challengeId: 4,
      text: 'uno',
      audioSrc: '/es/es_one.mp3',
      isCorrect: false,
    },
    {
      challengeId: 5,
      text: 'siete',
      audioSrc: '/es/es_seven.mp3',
      isCorrect: true,
    },
    {
      challengeId: 5,
      text: 'seis',
      audioSrc: '/es/es_six.mp3',
      isCorrect: false,
    },
    {
      challengeId: 5,
      text: 'ocho',
      audioSrc: '/es/es_eight.mp3',
      isCorrect: false,
    },
    {
      challengeId: 6,
      text: 'rojo',
      audioSrc: '/es/es_red.mp3',
      isCorrect: true,
    },
    {
      challengeId: 6,
      text: 'verde',
      audioSrc: '/es/es_green.mp3',
      isCorrect: false,
    },
    {
      challengeId: 6,
      text: 'azul',
      audioSrc: '/es/es_blue.mp3',
      isCorrect: false,
    },
    {
      challengeId: 7,
      text: 'azul',
      audioSrc: '/es/es_blue.mp3',
      isCorrect: true,
    },
    {
      challengeId: 7,
      text: 'amarillo',
      audioSrc: '/es/es_yellow.mp3',
      isCorrect: false,
    },
    {
      challengeId: 7,
      text: 'negro',
      audioSrc: '/es/es_black.mp3',
      isCorrect: false,
    },
    {
      challengeId: 8,
      text: 'madre',
      audioSrc: '/es/es_mother.mp3',
      isCorrect: true,
    },
    {
      challengeId: 8,
      text: 'padre',
      audioSrc: '/es/es_father.mp3',
      isCorrect: false,
    },
    {
      challengeId: 8,
      text: 'hermana',
      audioSrc: '/es/es_sister.mp3',
      isCorrect: false,
    },
    {
      challengeId: 9,
      text: 'hermano',
      audioSrc: '/es/es_brother.mp3',
      isCorrect: true,
    },
    {
      challengeId: 9,
      text: 'tío',
      audioSrc: '/es/es_uncle.mp3',
      isCorrect: false,
    },
    {
      challengeId: 9,
      text: 'primo',
      audioSrc: '/es/es_cousin.mp3',
      isCorrect: false,
    },
    {
      challengeId: 10,
      text: 'hola',
      audioSrc: '/es/es_hello.mp3',
      isCorrect: true,
    },
    {
      challengeId: 10,
      text: 'gracias',
      audioSrc: '/es/es_thanks.mp3',
      isCorrect: false,
    },
    {
      challengeId: 10,
      text: 'por favor',
      audioSrc: '/es/es_please.mp3',
      isCorrect: false,
    },
    {
      challengeId: 11,
      text: 'adiós',
      audioSrc: '/es/es_goodbye.mp3',
      isCorrect: true,
    },
    {
      challengeId: 11,
      text: 'buenos días',
      audioSrc: '/es/es_good_morning.mp3',
      isCorrect: false,
    },
    {
      challengeId: 11,
      text: 'buenas noches',
      audioSrc: '/es/es_good_night.mp3',
      isCorrect: false,
    },
  ];
